FROM node:8-stretch

ENV PORT 3000
ENV NODE_HEAPDUMP_OPTIONS nosignal

WORKDIR "/app"

# Bundle app source
COPY . /app
COPY run-dev /bin
RUN chmod 777 /bin/run-dev && apt-get update && apt-get install bc
