version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nodejsbackendforfrontend-express-run"
    container_name: "nodejsbackendforfrontend-express-run"
    ports: 
        - "3000:3000"
        - "9229:9229"
    volumes:
      - .:/app
      - node_modules:/app/node_modules 
    environment:
      NODE_ENV: "development"
      PORT: 3000
volumes:
  node_modules:
